name: Deploy new release to pypi

on:
  release:
    types: [ published ]
    
jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt-get -y install libolm-dev
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry
      
      - name: Install dependencies
        run: |
          poetry update

      - name: Run linting
        run: |
          poetry run pylint --rcfile .pylintrc matrix_photos

      - name: Run tests
        run: |
          poetry run pytest tests

      - name: Bump version
        run: |
          version=${{ github.event.release.tag_name }}
          poetry version $version

      - name: Commit version
        uses: EndBug/add-and-commit@v7.1.2
        with:
          add: '["pyproject.toml"]'
          branch: 'main'
          message: 'bump version up to ${{ github.event.release.tag_name }}'

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.5
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
