name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    
jobs:
  lint-and-test:
    name: build and run linting and checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Install required packages
        run: |
          sudo apt-get -y install libolm-dev
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry
      
      - name: Install dependencies
        run: |
          poetry update

      - name: Run linting
        run: |
          poetry run pylint --rcfile .pylintrc matrix_photos

      - name: Run tests
        run: |
          poetry run pytest tests
